sudo: required

services:
  - docker

before_script:
  - docker-compose config

script:
  - docker-compose run --rm -v .:/liquibase/changelog liquibase

after_script:
  - docker-compose down
