version: "3.7"

x-common-env: &common-env
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  POSTGRES_DB: ${POSTGRES_USER:-postgres}

services:
  postgres:
    container_name: liquibase_postgres
    image: postgres:latest
    environment: 
      <<: *common-env
    ports: 
      - "5432:5432"

  gradle:
    container_name: liquibase_gradle
    image: gradle:latest
    depends_on: 
      - postgres
    environment: 
      <<: *common-env
    volumes:
      - ".:/home/gradle/project"
    working_dir: "/home/gradle/project"
    entrypoint: ["gradle"]
    command: ["waitForDb", "update", "test"]